language: java
jdk: openjdk8
sudo: true
before_script:
- cd API_Discovery
script:
- mvn clean install -B
after_script:
- cd ..
before_script:
- cd customer
script:
- mvn clean install -B
after_script:
- cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)