language: java
jdk: openjdk8
before_script:
 - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
 - echo "Clean up activity can be done here !."

stages:
 - build
 - package


API_Discovery:
 stage: build
 before_script:
  - cd API_Discovery
 script:
  - mvn compile

API_Discovery:
 stage: package
 before_script:
  - cd API_Discovery
 script:
  - mvn package

customer:
 stage: build
 before_script:
  - cd customer
 script:
  - mvn compile

customer:
 stage: package
 before_script:
  - cd customer
 script:
  - mvn package